<h1 dir=rtl align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
چی بخریم؟
</font>
</h1>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
به یک پروژه‌ی متفاوت و کاربردی خوش آمدید! 🤩 در این مسئله گریزی به <i>سیستم‌های پیشنهاددهنده (Recommender Systems)</i> خواهیم زد و با استفاده از یک معماری یادگیری عمیق خلاقانه، مدلی پیاده خواهیم کرد که بتواند علاقه‌ی یک کاربر به یک کالای مشخص را تخمین بزند. با استفاده از این مدل خواهیم توانست لیستی از کالاها را به کاربر پیشنهاد دهیم که تاکنون آن‌ها را خریداری نکرده اما طبق الگوهایی که مدل بین کاربران و کالاها پیدا کرده به‌احتمال زیاد از آن‌ها خوشش خواهد آمد و به آن‌ها امتیاز بالایی خواهد داد. مجموعه‌داده‌ی پروژه نیز شامل داده‌های واقعی مربوط به کالاهای الکترونیکی موجود در <i>فروشگاه آنلاین آمازون (Amazon)</i> است.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="orange"><b>نکته:</b></font>
<font face="vazir" size=3>
اگرچه در این پروژه با داده‌های فروشگاه آنلاین سروکار داریم اما این مدل پیشنهاددهنده را می‌توان در دامنه‌های گوناگونی به کار گرفت. به‌عنوان مثال می‌توان سیستمی مشابه جهت پیشنهاد فیلم یا قطعه‌ی موسیقی به کاربران طراحی کرد.
</font>
</p>

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
داده‌های آموزشی در فایل <code dir=ltr>amazon_train.csv</code> در دسترس شما قرار گرفته است. این فایل شامل ۴ ستون است که به‌ترتیب بیانگر شناسه‌ی کاربر، شناسه‌ی محصول، امتیازی که کاربر به محصول داده و زمان ثبت امتیاز هستند. شبکه‌ای که در ادامه پیاده خواهیم کرد شناسه‌ی عددی کاربر و محصول را ورودی می‌گرد و امتیازی که کاربر به آن محصول می‌دهد را تخمین خواهد زد. ابتدا فایل مجموعه‌داده را به‌کمک <code>pandas</code> بخوانید.
</font>
</p>

In [12]:
import numpy as np
import pandas as pd

# Loading the dataset
valid = pd.read_csv('amazon_valid.csv')
train = pd.read_csv('amazon_train.csv')
test = pd.read_csv('amazon_test.csv')

In [39]:
train.head()

           UserID   ProductID  Rating   Timestamp  ProductEnc  UserEnc
0  A3HICVLF4PFFMN  0594481813    1.00  2014-05-05           0    59277
1  A2QBZA4S1ROX9Q  0594481813    0.50  2013-05-25           0    41167
2   AT09WGFUM934H  0594481813    0.50  2013-08-31           0    85549
3   AGAKHE014LQFU  0594481813    0.50  2013-09-18           0    77047
4  A1S6B5QFWGVL5U  0594481813    0.75  2013-06-27           0    18672

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌پردازش
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
پس از بررسی و تحلیل داده‌هایی که در اختیارتان گرفته ممکن است به پیش‌پردازش‌های مختلفی نیاز پیدا کنید و ایده‌های گوناگونی را پیاده کنید. با این حال، دو پیش‌پردازش اصلی که حتماً به آن‌ها نیاز خواهید داشت را در ادامه شرح داده‌ایم.
</font>
</p>

<h3 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
کدگذاری
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
از آن‌جا که شناسه‌های کاربر (<code dir=ltr>UserID</code>) و محصول (<code dir=ltr>ProductID</code>) به‌صورت رشته‌ای هستند، نیاز است آن‌ها را به‌شکل اعداد مرتب کدگذاری کنیم. بنابراین ابتدا با استفاده از کلاس <code>LabelEncoder</code> موجود در کتابخانه‌ی <code>sklearn</code> هر کدام از این ستون‌ها را کدگذاری کنید. پیشنهاد می‌شود حاصل را در ستون‌های مجزایی به‌نام‌های <code>UserEnc</code> و <code>ProductEnc</code> ذخیره کنید.
</font>
</p>

In [30]:
from sklearn.preprocessing import LabelEncoder

product_le = LabelEncoder()
user_le = LabelEncoder()

train['ProductEnc'] = product_le.fit_transform(train['ProductID'])
train['UserEnc'] = user_le.fit_transform(train['UserID'])

# if test exists
test['ProductEnc'] = product_le.transform(test['ProductID'])
test['UserEnc'] = user_le.transform(test['UserID'])
valid['UserEnc'] = user_le.transform(valid['UserID'])
valid['ProductEnc'] = product_le.transform(valid['ProductID'])

In [19]:
train.head(20)

            UserID   ProductID  Rating   Timestamp  ProductEnc  UserEnc
0   A3HICVLF4PFFMN  0594481813    1.00  2014-05-05           0    59277
1   A2QBZA4S1ROX9Q  0594481813    0.50  2013-05-25           0    41167
2    AT09WGFUM934H  0594481813    0.50  2013-08-31           0    85549
3    AGAKHE014LQFU  0594481813    0.50  2013-09-18           0    77047
4   A1S6B5QFWGVL5U  0594481813    0.75  2013-06-27           0    18672
5   A2IDCSC6NVONIZ  0972683275    1.00  2013-04-30           1    35949
6   A3BMUBUC1N77U8  0972683275    0.75  2013-11-23           1    55248
7    AVRFGGCCCR6QU  0972683275    0.75  2010-08-30           1    87318
8    AYQNWE3AX4H08  0972683275    1.00  2013-07-18           1    89229
9   A3P24ZSF9IQRJJ  0972683275    1.00  2014-06-13           1    64167
10   AQBLWW13U66XD  0972683275    1.00  2013-08-04           1    83767
11   AUKEU9CW56TT4  0972683275    1.00  2014-04-07           1    86558
12  A23A7OH3AM0PDA  0972683275    0.75  2011-01-27           1    26010
13   A5O0P0JV6PLU3  0972683275    1.00  2012-11-25           1    70104
14  A2KQDWZZUBBNOJ  0972683275    0.75  2011-05-31           1    37502
15  A27XULAA9X5ZGQ  0972683275    1.00  2012-02-17           1    29106
16  A3IIGCFLKVFW8M  0972683275    1.00  2014-02-27           1    59923
17  A3VKO21KYDJQ2W  0972683275    0.50  2011-07-12           1    68572
18  A1MSO6LERG39PC  0972683275    1.00  2012-09-13           1    15128
19   A1980MGZXSGJP  0972683275    1.00  2013-02-17           1     6139

<h3 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
نرمال‌سازی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
اکنون مقادیر ستون <code>Rating</code> را به‌کمک <code>MinMaxScaler</code> کتابخانه‌ی <code>sklearn</code> نرمال کنید تا مقادیر آن به بازه‌ی ۰ تا ۱ نگاشت شود.
</font>
</p>

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

train['Rating'] = scaler.fit_transform(train[['Rating']])
valid['Rating'] = scaler.fit_transform(valid[['Rating']])

KeyError: "None of [Index(['Rating'], dtype='object')] are in the [columns]"

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدل‌سازی
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
حال نوبت به مدل‌سازی می‌رسد. ساختار پیشنهادی ما به این شکل است که شبکه دو ورودی خواهد داشت: شناسه‌ی کاربر و شناسه‌ی کالا. برای هر کدام از این شناسه‌ها یک لایه‌ی تعبیه‌ساز (<code>Embedding</code>) جداگانه در نظر می‌گیریم تا به‌ازای هر کاربر یا کالا، یک بردار تعبیه‌ی بامعنا ساخته شود. خروجی هر لایه‌ی تعبیه به‌کمک یک لایه‌ی <code>Flatten</code> مسطح خواهد شد. پس از این مراحل، دو بردار بازنمایی کالا و کاربر در اختیار شما قرار می‌گیرد و می‌توانید پس از آن معماری دلخواه خود را پیاده کنید. به‌عنوان مثال می‌توانید بردار تعبیه‌ی کالا را در بردار تعبیه‌ی کاربر ضرب نقطه‌ای کنید (به‌کمک لایه‌ی <code>dot</code>) و حاصل را از تابع فعال‌ساز <code>sigmoid</code> عبور دهید تا خروجی شبکه یعنی امتیاز کاربر به آن کالا بین ۰ تا ۱ تولید شود. بنابراین ابتدا این ساختار را به‌کمک مدل تابعی (Functional) کراس پیاده‌سازی کنید.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="orange"><b>نکته:</b></font>
<font face="vazir" size=3>
دست شما کاملاً برای ایجاد تغییرات در این ساختار باز است. به‌عنوان مثال می‌توانید علاوه بر تولید بردارهای تعبیه، به‌کمک لایه‌های اضافه‌ی <code>Embedding</code> (با اندازه‌ی بردار ۱) یک مقدار بایاس هم برای هر کاربر یا کالا تولید کنید. در نهایت می‌توانید بایاس کاربر، بایاس کالا و حاصل ضرب نقطه‌ای را به‌کمک یک لایه‌ی <code>add</code> جمع کنید. به‌عنوان ایده‌ای دیگر می‌توانید به‌جای آن‌که دو بردار تعبیه را در یکدیگر ضرب کنید از عملیات‌های دیگری همچون الحاق (<code>Concatenate</code>) استفاده کنید. همچنین می‌توانید بر تعداد لایه‌ها بی‌افزایید، یا روش مقداردهی اولیه‌ی وزن‌ها یا رگولاریزیشن هر لایه را تنظیم کنید.
</font>
</p>

In [26]:
import keras
from keras.layers import Input, Embedding, Flatten, Dot, Activation
from keras.models import Model

n_users = train['UserEnc'].max() + 1
n_products = train['ProductEnc'].max() + 1
embedding_size = 50

user_input = Input(shape=(1,), name='user_input')
product_input = Input(shape=(1,), name='product_input')

user_embedding = Embedding(n_users, embedding_size)(user_input)
product_embedding = Embedding(n_products, embedding_size)(product_input)

user_vec = Flatten()(user_embedding)
product_vec = Flatten()(product_embedding)

dot_user_product = Dot(axes=1)([user_vec, product_vec])
output = Activation('sigmoid')(dot_user_product)

model = Model(inputs=[user_input, product_input], outputs=output)

model.compile(
    optimizer='adam',
    loss='binary_crossentropy'
)
model.summary()

Model: "functional_4"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ user_input          │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ product_input       │ (None, 1)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_8         │ (None, 1, 50)     │  4,502,500 │ user_input[0][0]  │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding_9         │ (None, 1, 50)     │  2,438,450 │ product_input[0]… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_8 (Flatten) │ (None, 50)        │          0 │ embedding_8[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ flatten_9 (Flatten) │ (None, 50)        │          0 │ embedding_9[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dot_4 (Dot)         │ (None, 1)         │          0 │ flatten_8[0][0],  │
│                     │                   │            │ flatten_9[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ activation_4        │ (None, 1)         │          0 │ dot_4[0][0]       │
│ (Activation)        │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 6,940,950 (26.48 MB)

 Trainable params: 6,940,950 (26.48 MB)

 Non-trainable params: 0 (0.00 B)

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
پس از طراحی معماری شبکه، می‌توانید آن را با ورودی دادن یک لیست شامل دو لیست شناسه‌ی کاربر و شناسه‌ی کالا آموزش دهید. متغیر هدف نیز همان ستون <code>Rating</code> خواهد بود. همچنین در صورتی‌که در لایه‌ی آخر از تابع فعال‌ساز <code>sigmoid</code> برای نورون خروجی استفاده کرده باشید می‌توانید از تابع زیان <code>binary_crossentropy</code> بهره ببرید. در صورت علاقه و نیاز می‌توانید از هر تکنیک دلخواهی در فرآیند آموزش مدل خود استفاده کنید.
</font>
</p>

In [27]:
history = model.fit(
    [train['UserEnc'], train['ProductEnc']],
    train['Rating'],
    epochs=10,
    batch_size=32,
    validation_split=0.1
)

Epoch 1/10
25572/25572 ━━━━━━━━━━━━━━━━━━━━ 1048s 41ms/step - loss: 0.6892 - val_loss: 0.6933
Epoch 2/10
25572/25572 ━━━━━━━━━━━━━━━━━━━━ 1054s 41ms/step - loss: 0.5078 - val_loss: 0.6935
Epoch 3/10
25572/25572 ━━━━━━━━━━━━━━━━━━━━ 1056s 41ms/step - loss: 0.3655 - val_loss: 0.6937
Epoch 4/10
25572/25572 ━━━━━━━━━━━━━━━━━━━━ 1070s 42ms/step - loss: 0.2986 - val_loss: 0.6940
Epoch 5/10
25572/25572 ━━━━━━━━━━━━━━━━━━━━ 1070s 42ms/step - loss: 0.2608 - val_loss: 0.6942
Epoch 6/10
25572/25572 ━━━━━━━━━━━━━━━━━━━━ 1081s 42ms/step - loss: 0.2411 - val_loss: 0.6945
Epoch 7/10
25572/25572 ━━━━━━━━━━━━━━━━━━━━ 1096s 43ms/step - loss: 0.2307 - val_loss: 0.6947
Epoch 8/10
25572/25572 ━━━━━━━━━━━━━━━━━━━━ 1105s 43ms/step - loss: 0.2251 - val_loss: 0.6948
Epoch 9/10
25572/25572 ━━━━━━━━━━━━━━━━━━━━ 1108s 43ms/step - loss: 0.2224 - val_loss: 0.6950
Epoch 10/10
25572/25572 ━━━━━━━━━━━━━━━━━━━━ 1110s 43ms/step - loss: 0.2203 - val_loss: 0.6952

In [32]:
valid.head()

           UserID   ProductID  Rating   Timestamp  UserEnc  ProductEnc
0  A3SBTW3WS4IQSN  B005FDXMJS     1.0  2014-07-23    66384       32700
1  A1NXNMRAVPGTO3  B00F9FCW7K     1.0  2014-07-23    15871       47381
2  A1VP1KVX7Y4PHQ  B00FEE7B1I     4.0  2014-07-22    20933       47462
3  A1XEB94731LGAR  B007VGGIRK     5.0  2014-07-22    22067       38253
4  A2I3XS9TO93Q0F  B00JCE14AU     4.0  2014-07-22    35766       48640

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌بینی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
دو فایل دیگر به نام‌های <code>amazon_valid.csv</code> و <code>amazon_test.csv</code> نیز به‌عنوان مجموعه‌ی اعتبارسنجی و آزمون در اختیار شما قرار گرفته است. مدل شما باید بتواند به‌ازای هر جفت کاربر و کالا، امتیازی که آن کاربر به آن کالا می‌دهد را به‌درستی تخمین بزند. ساختار این مجموعه‌ها نیز مشابه با مجموعه‌ی آموزشی است با این تفاوت که برچسب حقیقی داده‌های آزمون در دسترس شما نیست و ارزیابی مدل شما بر روی داده‌های آزمون در سامانه‌ی داوری کوئرا انجام می‌پذیرد. با این حال، توزیع داده‌ها بین مجموعه‌ی اعتبارسنجی و آزمون بسیار مشابه است و اگر مدل شما برای نمونه‌های اعتبارسنجی به عملکرد قابل قبولی برسد به احتمال زیاد برای نمونه‌های آزمون نیز همین‌گونه خواهد بود.
</font>
</p>


<h3 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
هدفی که در این نوع مسئله در نظر گرفته‌ایم این است که مدل شما تا چه‌اندازه می‌تواند کالاهایی که کاربر به آن‌ها امتیاز بالا (۴ یا ۵) می‌دهد را به‌درستی تشخیص دهد، بنابراین
عملکرد مدل شما در سامانه‌ی داوری به این‌گونه ارزیابی خواهد شد که برچسب‌های <code>5</code> و <code>4</code> به‌عنوان دسته‌ی مثبت و سایر برچسب‌ها به‌عنوان دسته‌ی منفی در نظر گرفته می‌شود.
سپس از معیار <code>Precision</code> جهت ارزیابی مدل شما استفاده خواهد شد که در واقع نسبت تعداد پیشنهادات مثبت درست (مدل تشخیص داده که کاربر به کالا امتیاز بالا می‌دهد و واقعاً این‌گونه بوده) به کل پیشنهادات مثبت مدل را می‌شمارد.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazir" size=3>
 جهت کسب امتیاز کامل نیاز است تا پاسخ شما حداقل امتیاز <code>80</code> را با توجه به معیار معرفی‌شده کسب نماید.
</font>
</p>

In [36]:
from sklearn.metrics import precision_score

y_prob = model.predict([valid['UserEnc'], valid['ProductEnc']])
y_pred = (y_prob >= 0.5).astype(int).ravel()
valid['Label'] = (valid['Rating'] >= 0.75).astype(int)
precision = precision_score(valid['Label'], y_pred)
print("Validation Precision:", precision)

2810/2810 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step
Validation Precision: 0.8291809338242668

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ساختار خروجی برای نمونه‌های آزمون
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
 پیش‌بینی مدل خود را برای نمونه‌های آزمون به‌شکل امتیازی بین ۱ تا ۵ تولید کرده و در ستون <code>Rating</code> یک دیتافریم با نام <code>submission</code> در قالب جدول زیر ذخیره کنید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>UserID</code>|شناسه‌ی کاربر (مشابه با نمونه‌ی آزمون)|
|<code>ProductID</code>|شناسه‌ی کالا (مشابه با نمونه‌ی آزمون)|
|<code>Rating</code>|امتیاز کاربر به کالا از ۱ تا ۵ (پیش‌بینی مدل)|
    
</font>
</div>
</center>

In [57]:
test_pred_scaled = model.predict([test['UserEnc'], test['ProductEnc']]).ravel()

# map from [0,1] to [1,5]
test_pred_rating = test_pred_scaled * 4 + 1

# optional safety clip
test_pred_rating = np.clip(test_pred_rating, 1, 5)

submission = pd.DataFrame({
    'UserID': test['UserID'],
    'ProductID': test['ProductID'],
    'Rating': test_pred_rating.astype(int)
})

submission.to_csv('submission.csv', index=False)
print(submission.head())

2805/2805 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step
           UserID   ProductID  Rating
0  A2Y3A341VDK37H  B00HFI55N2       2
1  A240FRPD4MEXND  B00KIMX4EY       2
2  A3SBTW3WS4IQSN  B001IF252M       3
3   A1QCZQTJNK3MU  B00J46VVKE       2
4  A16JT7E5121OAB  B00JZC972Q       2

In [54]:
test_pred_scaled = model.predict([test['UserEnc'], test['ProductEnc']]).ravel()

print("min:", test_pred_scaled.min())
print("max:", test_pred_scaled.max())
print("mean:", test_pred_scaled.mean())
print(test_pred_scaled[:20])

2805/2805 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step
min: 1.4797759e-07
max: 1.0
mean: 0.7212662
[0.4996667  0.48420525 0.5762102  0.47937793 0.49149323 0.4702936
 0.47246873 0.5051782  0.5074475  0.47236446 0.48139158 0.5065893
 0.5120538  0.5066946  0.47401652 0.46362942 0.5000193  0.4778626
 0.4957969  0.4625204 ]

In [58]:
submission

               UserID   ProductID  Rating
0      A2Y3A341VDK37H  B00HFI55N2       2
1      A240FRPD4MEXND  B00KIMX4EY       2
2      A3SBTW3WS4IQSN  B001IF252M       3
3       A1QCZQTJNK3MU  B00J46VVKE       2
4      A16JT7E5121OAB  B00JZC972Q       2
...               ...         ...     ...
89727  A37Z65SZVT0TVB  B00005AR4L       2
89728  A3PLX6PTM2ERKL  B00004Z6PI       4
89729  A3TRPVAGT3NWBS  B00005NVPW       4
89730   AY8Q1X7G96HV5  B000059MSI       4
89731  A3IBOQ8R44YG9L  B00004TDMX       4

[89732 rows x 3 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد. همچنین اگر از گوگل کولب استفاده می‌کنید، در صورت نیاز به پشتیبانی حتماً آخرین نسخه از نت‌بوک را به‌صورت دستی دانلود کرده و داخل فایل ارسالی قرار دهید یا لینک کولب را با ما به‌اشتراک بگذارید.
</font>
</p>

In [59]:
import zipfile
import joblib
import os

if not os.path.exists(os.path.join(os.getcwd(), 'what_to_buy.ipynb')):
    %notebook -e what_to_buy.ipynb

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

submission.to_csv('submission.csv', index=False)
file_names = ['what_to_buy.ipynb', 'submission.csv']
compress(file_names)

File Paths:
['what_to_buy.ipynb', 'submission.csv']

<h2 dir=rtl align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بیشتر بدانید:
سیستم پیشنهاددهنده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
برای پیشنهاد کالای جدید به یک کاربر روش‌های مختلفی وجود دارد، اما یک راه ساده این است که از تخمین امتیازی که مدل به‌ازای هر جفت کاربر و کالا می‌دهد استفاده کنیم.
به‌ازای یک کاربر به‌کمک مدل خود تخمین می‌زنیم که وی از بین کالاهایی که تاکنون خریداری نکرده، کدام‌ها را بیشتر از همه دوست خواهد داشت و امتیاز بالاتری به آن‌ها خواهد داد. بنابراین می‌توانیم این کالاها را به او پیشنهاد دهیم و به‌احتمال زیاد از تعدادی از آن‌ها خوشش خواهد آمد. البته این موضوع نمی‌تواند مستقیماً به این معنی باشد که آن کالا را خریداری می‌کند. به‌عنوان مثال شاید یک کالای گران‌قیمت را پیشنهاد دهیم که همگی از آن خوشمان می‌آید اما بسیاری قدرت خرید آن را نداریم! 🫠
</font>
</p>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
<span style="color:green"><b>راهنمایي:</b></span>
برای تولید پیش‌بینی به‌ازای یک کاربر ابتدا لیستی از کالاهایی که وی تاکنون خریداری نکرده را پیدا کنید. سپس جفت شناسه‌ی کدگذاری‌شده‌ی کاربر و هر یک از این کالاها را به مدل ورودی بدهید تا امتیاز کاربر به هر کدام از آن کالاها تخمین زده شود. در نهایت می‌توان <code>n</code> کالایی که منجر به بیشترین امتیاز (خروجی مدل) شده را انتخاب کرد و به وی پیشنهاد داد.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
<span style="color:purple"><b>🧐 بیشتر بی‌اندیشیم:</b></span>
چه روش‌های دیگری جهت پیشنهاد کالا به یک کاربر مشخص به ذهن‌تان می‌رسد؟ آیا می‌توان مستقیماً‌ از بردارهای تعبیه‌ی هر کالا یا کاربر جهت پیشنهاد استفاده کرد؟ به چه روش‌های می‌توان کاربران مشابه با یک کاربر را پیدا کرده و براساس تجربه یا الگوی خرید آن‌ها به کاربر کالاهایی را پیشنهاد داد؟ پیشنهاد می‌کنیم به این موضوعات بیشتر فکر کرده و نظرات خود را از طریق بخش دیدگاه عمومی صفحه‌ی پروژه در کوئرا با دیگران به‌اشتراک بگذارید. چه بهتر که ایده‌های خود را به‌شکل عملی نیز آزمایش کنید.
</font>
</p>